/** Plain-language messages shown to people. No jargon. */
export const MSG = {
  badRequest: "The request was empty or malformed.",
  blocked: "Request blocked.",
  notConnected: "Connect your Cloudflare account first.",
  notFound: "Not found.",
  slowDown: "That's a lot of requests at once. Wait a minute and try again.",
  tooBig: "That request is too large.",
  serverBroke: "Something broke on our side. Try again.",
  badToken: "That doesn't look like a Cloudflare token. Copy it again from Cloudflare.",
  tokenRejected: "Cloudflare didn't accept this token. Check you copied all of it and that it hasn't been deleted or expired.",
  noAccount: "This token can't see any Cloudflare account. Create it again with the button, which fills in every permission.",
  noPermission: "Your token is missing a permission for this.",
  notAllowed: "Cloudflare says this isn't allowed on your account or plan.",
  rateLimited: "Cloudflare is busy with too many requests. Wait a minute and try again.",
  offline: "Couldn't reach Cloudflare. Check your connection and try again.",
  unreadable: "Cloudflare sent an unreadable reply.",
  connectionExpired: "Your saved connection stopped working. Connect again.",
  signInExpired: "Your Cloudflare sign-in expired. Sign in again.",
  notYourSite: "That website isn't on your account.",
  pickSite: "Pick a website first.",
  proposalInvalid: "This suggestion isn't valid any more. Ask again.",
  proposalExpired: "This suggestion expired. Ask again and confirm within 15 minutes.",
  typeMessage: "Type a message first.",
  aiNoPermission: "The assistant needs Cloudflare AI access on your token. Create a new token with the button (it's free) and reconnect.",
  aiLimit: "You've used today's free Cloudflare AI allowance. It resets at midnight UTC. Everything else still works.",
  aiDown: "The assistant isn't available right now. Try again in a moment.",
  aiTooLong: "That took more steps than expected. Try asking in a simpler way.",
} as const;
